#!/usr/bin/env Rscript
# scripts/sims-variance-het-sigma-bimodal-v2/4_make_latex_table.R
#
# Reads combined_results.rds (output of 2_collect_results.R) and prints
# the LaTeX source for \label{tab:bimodal-satt-coverage-v2}.
#
# Usage:
#   Rscript 4_make_latex_table.R [output_name]
#   output_name defaults to "sims-variance-het-sigma-bimodal-v2"
#
# Run 2_collect_results.R first if combined_results.rds does not exist.

suppressPackageStartupMessages({
  library(dplyr)
  library(here)
})

args        <- commandArgs(trailingOnly = TRUE)
output_name <- if (length(args) >= 1) args[[1]] else "sims-variance-het-sigma-bimodal-v2"

combined_rds <- here::here("data/outputs", output_name, "combined_results.rds")
if (!file.exists(combined_rds))
  stop("combined_results.rds not found. Run 2_collect_results.R first.\n  Expected: ", combined_rds)

# -------------------------------------------------------------------
# Load
# -------------------------------------------------------------------
message("Reading combined results from: ", combined_rds)
df <- readRDS(combined_rds)

n_iters <- length(unique(df$runID))
message("Unique iterations: ", n_iters)

# -------------------------------------------------------------------
# SATT coverage with V_E-only CI
# -------------------------------------------------------------------
df2 <- df %>%
  filter(status == "Success", !is.na(V_E), !is.na(SATT)) %>%
  mutate(
    SE_VE  = sqrt(pmax(0, V_E)),
    covers = att_est - 1.96 * SE_VE <= SATT &
             SATT <= att_est + 1.96 * SE_VE
  )

overlap_order      <- c("very_low", "low", "mid", "high", "very_high")
overlap_labels_tex <- c("Very low", "Low", "Mid", "High", "Very high")

summ <- df2 %>%
  group_by(inference_method, deg_overlap, sigma1_extra) %>%
  summarise(n = n(), coverage = mean(covers), avg_SE = mean(SE_VE, na.rm = TRUE),
            .groups = "drop")

s1_vals <- sort(unique(summ$sigma1_extra))
message("sigma1_extra values: ", paste(s1_vals, collapse = ", "))

# -------------------------------------------------------------------
# Helper: one table row
# -------------------------------------------------------------------
make_row <- function(overlap, s1, methods = c("homo", "het", "alt_common", "alt_tt")) {
  get <- function(m, col) {
    v <- summ %>%
      filter(deg_overlap == overlap, sigma1_extra == s1,
             inference_method == m) %>%
      pull(!!col)
    if (length(v) == 0) return(NA_real_)
    v[[1]]
  }
  covs <- sapply(methods, function(m) get(m, "coverage"))
  ses  <- sapply(methods, function(m) get(m, "avg_SE"))

  fmt <- function(x) if (is.na(x)) "---" else sprintf("%.3f", x)
  paste0(
    " & ", overlap_labels_tex[match(overlap, overlap_order)],
    paste(sprintf(" & %s", sapply(covs, fmt)), collapse = ""),
    paste(sprintf(" & %s", sapply(ses,  fmt)), collapse = ""),
    " \\\\"
  )
}

build_block <- function(s1) {
  rows <- sapply(overlap_order, function(ov) make_row(ov, s1))
  paste(rows, collapse = "\n")
}

scen_label <- function(s1) {
  if (s1 == 0) return("$\\sigma_1{=}\\sigma_0$")
  sprintf("$\\sigma_1{=}\\sigma_0{+}%.1f$", s1)
}

# -------------------------------------------------------------------
# Caption and label
# -------------------------------------------------------------------
is_v2      <- grepl("v2", output_name)
design_str <- if (is_v2) "Bimodal $\\sigma_0$ v2 ($A=5$, $h^2=0.08$)" else
                          "Bimodal $\\sigma_0$ v1 ($A=1$, $h^2=0.08$)"
label_str  <- if (is_v2) "tab:bimodal-satt-coverage-v2" else "tab:bimodal-satt-coverage"

caption <- sprintf(
  paste0(
    "SATT coverage (nominal 0.95) and average estimated SE $(\\sqrt{\\hat{V}_E})$ for four variance\n",
    "estimators. %s design, $k=2$ adaptive matching, $\\approx$%d replications.\n",
    "All \\texttt{alt-tt} results include the $K/(K+1)$ bias correction."
  ),
  design_str, n_iters
)

# -------------------------------------------------------------------
# Print LaTeX
# -------------------------------------------------------------------
cat("% Generated by:", output_name, "\n")
cat("% Run: Rscript scripts/sims-variance-het-sigma-bimodal-v2/4_make_latex_table.R\n\n")

cat("\\begin{table}[ht]\n")
cat("\\centering\n")
cat(sprintf("\\caption{%s}\n", caption))
cat(sprintf("\\label{%s}\n", label_str))
cat("\\begin{tabular}{llcccccccc}\n")
cat("\\toprule\n")
cat(" & & \\multicolumn{4}{c}{SATT coverage} & \\multicolumn{4}{c}{Avg $\\sqrt{\\hat{V}_E}$} \\\\\n")
cat("\\cmidrule(lr){3-6}\\cmidrule(lr){7-10}\n")
cat("Scenario & Overlap & homo & het & alt-c & alt-tt & homo & het & alt-c & alt-tt \\\\\n")
cat("\\midrule\n")

for (i in seq_along(s1_vals)) {
  s1 <- s1_vals[i]
  sl <- scen_label(s1)
  cat(sprintf("\\multirow{5}{*}{\\shortstack[l]{%d:\\\\%s}}\n", i, sl))
  cat(build_block(s1), "\n")
  if (i < length(s1_vals)) cat("\\midrule\n")
}

cat("\\bottomrule\n")
cat("\\end{tabular}\n")
cat("\\end{table}\n")
